global using System.Data;
global using System.Text;
global using EmployeeAccountingSystem.Configurations;
global using EmployeeAccountingSystem.Data.Repositories.Interfaces;
global using EmployeeAccountingSystem.Data.Repositories;
global using EmployeeAccountingSystem.Models.DTOs;
global using EmployeeAccountingSystem.Models;
global using Microsoft.Data.SqlClient;
global using Microsoft.Extensions.Options;